### ISSUE TITLE
Pad numbers for SW_Cherry_MX and SW_Hybrid_Cherry_MX_Alps

### ISSUE THREAD

**Issue by adamws** [perigoso/keyswitch-kicad-library#4]
Due to difference in pad numbering between MX and Hybrid switches, footprint replacement is impossible.
I think that pad 1 for hybrid switch should be on the left as well (same for alps only switch).
![image](https://user-images.githubusercontent.com/12676586/107436096-5d6c2180-6b2d-11eb-90a7-c968bb49c0cc.png)
![image](https://user-images.githubusercontent.com/12676586/107436145-6f4dc480-6b2d-11eb-80e3-9305602168ab.png)

**Comment by perigoso** [comment]
I did this because of conflicting documentation I believe, where the manufacturer stated what they considered to be pin 1, I adopted it, resulting in conflicts, in hindsight i should've just chosen a numbering and used it everywhere, I shall change it when I have time, thank you for taking the time to open an issue.

**Comment by perigoso** [comment]
Corrected
