### ISSUE TITLE
Option for LEDs?

### ISSUE THREAD

**Issue by gauntface** [perigoso/keyswitch-kicad-library#6]
I might be missing something but is there any way to add LEDs to these footprints?

**Comment by perigoso** [comment]
The footprints don't come with LEDs, LEDs are complicated because adding support for all variants topically used would mean a lot of variants of every switch.

With these libs you're supposed to place the LEDs sperate form the switches, they will eventually get a marking in the user layer to help guide placement, but for now just place them offset from the center of the switch by 5.08mm I believe

**Comment by gauntface** [comment]
Can't argue with that :)

Thanks for the great lib.
